import {
  // status / checkmarks
  Circle,
  CircleDot,
  CircleCheckBig,
  CircleX,
  Check,
  X,
  Ban,
  Hourglass,
  Loader,
  Dot,
  // priority / flags
  Flag,
  FlagTriangleRight,
  TriangleAlert,
  CircleAlert,
  OctagonAlert,
  Star,
  Bookmark,
  BookmarkCheck,
  ArrowUp,
  Zap,
  Flame,
  Target,
  Award,
  // time / scheduling
  Clock,
  Clock3,
  Timer,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Sunrise,
  Moon,
  Sun,
  AlarmClock,
  Repeat,
  // work / activities / life categories
  Briefcase,
  Laptop,
  Mail,
  MessageSquare,
  Phone,
  Users,
  User,
  House,
  ShoppingCart,
  Utensils,
  Coffee,
  Dumbbell,
  Book,
  BookOpen,
  GraduationCap,
  Code,
  Wrench,
  Hammer,
  Paintbrush,
  Palette,
  FileText,
  Folder,
  Package,
  Truck,
  Plane,
  Car,
  Bike,
  Heart,
  Pill,
  Stethoscope,
  Dog,
  Cat,
  Music,
  Gift,
  DollarSign,
  CreditCard,
  Rocket,
  Trophy,
  Sparkles,
  Leaf,
  Compass,
  Wifi,
  Tag,
  ClipboardList,
  ClipboardCheck,
  Lock,
  Shield,
  Key,
  Search,
  Lightbulb,
  Send,
  Layers,
  Camera,
  Video,
  Headphones,
  Gamepad2,
  Puzzle,
  Printer,
  Globe,
  MapPin,
  Navigation,
  Wallet,
  Receipt,
  PiggyBank,
  ChartColumn,
  PenTool,
  Ruler,
  type LucideIcon,
} from 'lucide-react';

export const TASK_STAGE_ICON_NAMES = [
  'Circle', 'CircleDot', 'CircleCheckBig', 'CircleX', 'Check', 'X', 'Ban', 'Hourglass', 'Loader', 'Dot',
  'Flag', 'FlagTriangleRight', 'TriangleAlert', 'CircleAlert', 'OctagonAlert', 'Star', 'Bookmark',
  'BookmarkCheck', 'ArrowUp', 'Zap', 'Flame', 'Target', 'Award',
  'Clock', 'Clock3', 'Timer', 'Calendar', 'CalendarCheck', 'CalendarClock', 'CalendarDays', 'Sunrise',
  'Moon', 'Sun', 'AlarmClock', 'Repeat',
  'Briefcase', 'Laptop', 'Mail', 'MessageSquare', 'Phone', 'Users', 'User', 'House', 'ShoppingCart',
  'Utensils', 'Coffee', 'Dumbbell', 'Book', 'BookOpen', 'GraduationCap', 'Code', 'Wrench', 'Hammer',
  'Paintbrush', 'Palette', 'FileText', 'Folder', 'Package', 'Truck', 'Plane', 'Car', 'Bike', 'Heart',
  'Pill', 'Stethoscope', 'Dog', 'Cat', 'Music', 'Gift', 'DollarSign', 'CreditCard', 'Rocket', 'Trophy',
  'Sparkles', 'Leaf', 'Compass', 'Wifi', 'Tag', 'ClipboardList', 'ClipboardCheck', 'Lock', 'Shield',
  'Key', 'Search', 'Lightbulb', 'Send', 'Layers', 'Camera', 'Video', 'Headphones', 'Gamepad2', 'Puzzle',
  'Printer', 'Globe', 'MapPin', 'Navigation', 'Wallet', 'Receipt', 'PiggyBank', 'ChartColumn', 'PenTool',
  'Ruler',
] as const;

export type TaskStageIconName = (typeof TASK_STAGE_ICON_NAMES)[number];

export const TASK_STAGE_ICONS: Record<TaskStageIconName, LucideIcon> = {
  Circle, CircleDot, CircleCheckBig, CircleX, Check, X, Ban, Hourglass, Loader, Dot,
  Flag, FlagTriangleRight, TriangleAlert, CircleAlert, OctagonAlert, Star, Bookmark,
  BookmarkCheck, ArrowUp, Zap, Flame, Target, Award,
  Clock, Clock3, Timer, Calendar, CalendarCheck, CalendarClock, CalendarDays, Sunrise,
  Moon, Sun, AlarmClock, Repeat,
  Briefcase, Laptop, Mail, MessageSquare, Phone, Users, User, House, ShoppingCart,
  Utensils, Coffee, Dumbbell, Book, BookOpen, GraduationCap, Code, Wrench, Hammer,
  Paintbrush, Palette, FileText, Folder, Package, Truck, Plane, Car, Bike, Heart,
  Pill, Stethoscope, Dog, Cat, Music, Gift, DollarSign, CreditCard, Rocket, Trophy,
  Sparkles, Leaf, Compass, Wifi, Tag, ClipboardList, ClipboardCheck, Lock, Shield,
  Key, Search, Lightbulb, Send, Layers, Camera, Video, Headphones, Gamepad2, Puzzle,
  Printer, Globe, MapPin, Navigation, Wallet, Receipt, PiggyBank, ChartColumn, PenTool,
  Ruler,
};

// Safe accessor for arbitrary/possibly-stale strings coming off
// TaskStageDef.icon (a plain `string`, not the exact union) — returns
// undefined for unset or unrecognized names instead of indexing unsafely.
export function getTaskStageIcon(name: string | undefined): LucideIcon | undefined {
  if (!name) return undefined;
  return (TASK_STAGE_ICONS as Record<string, LucideIcon>)[name];
}
